version: "3.9"

services:
  db:
    image: postgres:16.1-alpine3.19
    restart: always
    env_file:
      - ./.env
    volumes:
      - ./scripts:/docker-entrypoint-initdb.d

    # environment:
    #   - POSTGRES_USER=postgres
    #   - POSTGRES_PASSWORD=postgres
    ports:
      - "7543:5432"
