"""initial table

Revision ID: 5471f3c6d380
Revises: 
Create Date: 2024-04-11 15:25:53.399364

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5471f3c6d380"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="False", nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["category.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "seasonal_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("start_date", sa.DateTime(), nullable=False),
        sa.Column("end_date", sa.DateTime(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("p_uid", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_digital", sa.Boolean(), server_default="False", nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column("seasonal_event", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), server_default="False", nullable=False),
        sa.Column(
            "stock_status", sa.String(), server_default="OUT_OF_STOCK", nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["category.id"],
        ),
        sa.ForeignKeyConstraint(
            ["seasonal_event"],
            ["seasonal_event.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
        sa.UniqueConstraint("p_uid"),
        sa.UniqueConstraint("slug"),
    )
    op.create_table(
        "product_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("price", sa.DECIMAL(precision=5, scale=2), nullable=False),
        sa.Column("sku", sa.UUID(), nullable=False),
        sa.Column("stock_qty", sa.Integer(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=True),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("sku"),
    )
    op.create_table(
        "product_image",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("alternative_text", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("product_line_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_line_id"],
            ["product_line.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_image")
    op.drop_table("product_line")
    op.drop_table("product")
    op.drop_table("seasonal_event")
    op.drop_table("category")
    # ### end Alembic commands ###
