"""associate table

Revision ID: 56ab6f4b84cd
Revises: 5471f3c6d380
Create Date: 2024-04-11 15:43:50.358011

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "56ab6f4b84cd"
down_revision = "5471f3c6d380"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attribute",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["product_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "attribute_value",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attribute_value", sa.String(), nullable=True),
        sa.Column("attribute_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["attribute_id"],
            ["attribute.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_product_type",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_type_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["product.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_type_id"],
            ["product_type.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_line_attribute_value",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("attribute_value_id", sa.Integer(), nullable=True),
        sa.Column("product_line_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["attribute_value_id"],
            ["attribute_value.id"],
        ),
        sa.ForeignKeyConstraint(
            ["product_line_id"],
            ["product_line.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_line_attribute_value")
    op.drop_table("product_product_type")
    op.drop_table("attribute_value")
    op.drop_table("product_type")
    op.drop_table("attribute")
    # ### end Alembic commands ###
